### ISSUE TITLE
Are path wrong or missing folders?

### ISSUE THREAD

**Issue by luizclaudius** [kairess/cat_hipsterizer#1]
Hi!

I'm just starting in image processing and downloaded your code and sorry if it's a newbie question.

When I ran preprocess.py detected two problems: the absence of CAT_00 folder and the respective dataset CAT_00.npy. Are missing these files or should I do anything before that?

Thanks and congratulations for your app.

**Comment by kairess** [comment]
@luizclaudius Hey!

Need to download dataset from Kaggle first.

https://www.kaggle.com/crawford/cat-dataset

**Comment by luizclaudius** [comment]
Oh, my!

I told it could be a newbie question. Hahaha.

Thank you for your patience.

Em qua, 13 de nov de 2019 20:47, Taehee Lee <notifications@github.com>
escreveu:
